version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "BOLSA_FAMILIA:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  producer:
    image: tiagokamegasawa/producer:0.0.1
    ports:
      - "8081:8080"
    links:
      - kafka:kafka
    deploy:
      replicas: 1
    environment:
      KAFKA_HOST: kafka:9092
      TOPIC_BOLSA: BOLSA_FAMILIA
      KAFKA_GROUP_ID: br.com.fiap.producer
      FILE_PATH: /bolsa-familia/
      FILE_NAME: 201911_BolsaFamilia_Pagamentos.csv
    volumes:
      - ${FILE_PATH}/${FILE_NAME}:${FILE_PATH}/${FILE_NAME}
    depends_on:
      - kafka

  consumidor-three:
    image: ronaldoleite/consumer-three:0.0.1
    ports:
      - "8080:8080"
    links:
      - kafka:kafka
    deploy:
      replicas: 1
    environment:
      KAFKA_HOST: kafka:9092
      TOPIC_BOLSA: BOLSA_FAMILIA
      KAFKA_GROUP_ID: br.com.fiap.consumerthree
    depends_on:
      - kafka